CREATE TABLE PRODUTO 
(ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
NOME VARCHAR(255), DESCRICAO VARCHAR(255));


insert into Produto values (1, 'Geladeira', 'Geladeira duas portas');
insert into Produto values (2, 'Ferro de passar', 'Ferro de passar roupa com vaporizador');

select * from produto

drop table produto